# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000  

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: my_actor_joint_1
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: my_actor_joint_2
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: my_actor_joint_3
  pid: {p: 100.0, i: 0.01, d: 10.0}
